### ISSUE TITLE
Date information in the univie-ling-handout class

### ISSUE THREAD

**Issue by DavidBitSource** [jspitz/univie-ling#2]
While the univie-ling-poster class provides the possibility to specify two date arguments: \date{<date>} for the date of the presentation and \eventdate{<date>} for the whole event, the univie-ling-handout class only provides \hoEventDate[<header>]{<event date>} to indicate the event or class itself.

A more differentiated way to specify the dates in the univie-ling-handout class would make sense: one for the entire event and one for the specific presentation. In this context, the possibility of either freely specifying the event date or, in accordance with the abbreviations already used, specifying the respective semester would make sense.

**Comment by jspitz** [comment]
We now have `\hoDate[header]{title}`
